### ISSUE TITLE
firecloud==0.16.25 install fails, cannot import of "six"

### ISSUE THREAD

**Issue by h836472** [BruneauLab-GladstoneInstitutes/computing-envs#4]
Dear Developers,

Moving along with monocle3 installation from docker, another bug popped up. installation of firecloud fails with the following error:

Collecting firecloud==0.16.25
  Downloading firecloud-0.16.25.tar.gz (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.0/49.0 KB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6r1n536u/firecloud_6f8c782be17149f7b85c877bbf35a961/setup.py", line 9, in <module>
          from setuptools.command.easy_install import six, rmtree_safe, rmtree, log
      ImportError: cannot import name 'six' from 'setuptools.command.easy_install' (/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by h836472** [comment]
changing 
 && pip3 install --ignore-installed firecloud==0.16.25 
to 
 && pip3 install --ignore-installed firecloud 

probably resolves this issue (and hopefully does not create another one)
